#!/bin/bash

LOG_FILE="/opt/zapretdeck/debug.log"

# Логирование
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG_FILE"
}

RESOLV_CONF="/etc/resolv.conf"
BACKUP_RESOLV_CONF="/opt/zapretdeck/resolv.conf.bak"

# Установка DNS
set_dns() {
    log "Установка DNS: 176.99.11.77, 80.78.247.254"

    # Если NetworkManager управляет resolv.conf
    if [ -f "$RESOLV_CONF" ] && grep -q "Generated by NetworkManager" "$RESOLV_CONF" && command -v nmcli >/dev/null; then
        active_con=$(nmcli -t -f NAME con show --active | head -n1)
        if [ -n "$active_con" ]; then
            nmcli con mod "$active_con" ipv4.dns "176.99.11.77 80.78.247.254" && nmcli con up "$active_con"
            if [ $? -eq 0 ]; then
                log "DNS установлен через nmcli для $active_con"
                exit 0
            else
                log "Ошибка: не удалось установить DNS через nmcli"
                exit 1
            fi
        else
            log "Ошибка: активное соединение NetworkManager не найдено"
            exit 1
        fi
    fi

    # Прямая запись в resolv.conf
    if [ -f "$RESOLV_CONF" ] && [ ! -f "$BACKUP_RESOLV_CONF" ]; then
        cp "$RESOLV_CONF" "$BACKUP_RESOLV_CONF"
        log "Создана резервная копия $RESOLV_CONF"
    fi

    cat <<EOF > "$RESOLV_CONF"
nameserver 176.99.11.77
nameserver 80.78.247.254
EOF
    if [ $? -eq 0 ]; then
        log "DNS успешно прописан в $RESOLV_CONF"
        exit 0
    else
        log "Ошибка: не удалось записать DNS в $RESOLV_CONF"
        exit 1
    fi
}

# Сброс DNS
unset_dns() {
    log "Сброс DNS"

    # Если NetworkManager управляет resolv.conf
    if [ -f "$RESOLV_CONF" ] && grep -q "Generated by NetworkManager" "$RESOLV_CONF" && command -v nmcli >/dev/null; then
        active_con=$(nmcli -t -f NAME con show --active | head -n1)
        if [ -n "$active_con" ]; then
            nmcli con mod "$active_con" ipv4.ignore-auto-dns no && nmcli con mod "$active_con" ipv4.dns "" && nmcli con up "$active_con"
            if [ $? -eq 0 ]; then
                log "DNS сброшен через nmcli для $active_con"
                exit 0
            else
                log "Ошибка: не удалось сбросить DNS через nmcli"
                exit 1
            fi
        else
            log "Ошибка: активное соединение NetworkManager не найдено"
            exit 1
        fi
    fi

    # Восстановление из бэкапа или установка дефолтных DNS
    if [ -f "$BACKUP_RESOLV_CONF" ]; then
        cp "$BACKUP_RESOLV_CONF" "$RESOLV_CONF" && rm -f "$BACKUP_RESOLV_CONF"
        if [ $? -eq 0 ]; then
            log "Восстановлен оригинальный $RESOLV_CONF"
            exit 0
        else
            log "Ошибка: не удалось восстановить $RESOLV_CONF"
            exit 1
        fi
    else
        cat <<EOF > "$RESOLV_CONF"
nameserver 8.8.8.8
nameserver 1.1.1.1
EOF
        if [ $? -eq 0 ]; then
            log "Установлены дефолтные DNS (Google/Cloudflare)"
            exit 0
        else
            log "Ошибка: не удалось записать дефолтные DNS в $RESOLV_CONF"
            exit 1
        fi
    fi
}

# Проверка аргументов
case "$1" in
    set)
        set_dns
        ;;
    unset)
        unset_dns
        ;;
    *)
        log "Ошибка: неверный аргумент '$1', ожидается 'set' или 'unset'"
        echo "Использование: $0 {set|unset}" >&2
        exit 1
        ;;
esac