#!/bin/bash

LOG_FILE="/opt/zapretdeck/debug.log"

# Логирование
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG_FILE"
}

RESOLV_CONF="/etc/resolv.conf"
BACKUP_RESOLV_CONF="/opt/zapretdeck/resolv.conf.bak"

# Установка DNS (общая функция)
set_dns() {
    local dns1="$1"
    local dns2="$2"
    local provider="$3"
    log "Установка DNS: $dns1, $dns2 ($provider)"

    # Через NetworkManager
    if [ -f "$RESOLV_CONF" ] && grep -q "Generated by NetworkManager" "$RESOLV_CONF" && command -v nmcli >/dev/null; then
        active_con=$(nmcli -t -f NAME con show --active | head -n1)
        if [ -n "$active_con" ]; then
            nmcli con mod "$active_con" ipv4.dns "$dns1 $dns2" && nmcli con up "$active_con"
            if [ $? -eq 0 ]; then
                log "DNS установлен через nmcli: $provider для $active_con"
                exit 0
            else
                log "Ошибка: не удалось установить DNS через nmcli ($provider)"
                exit 1
            fi
        else
            log "Ошибка: активное соединение NetworkManager не найдено"
            exit 1
        fi
    fi

    # Прямая запись в resolv.conf
    if [ -f "$RESOLV_CONF" ] && [ ! -f "$BACKUP_RESOLV_CONF" ]; then
        cp "$RESOLV_CONF" "$BACKUP_RESOLV_CONF"
        log "Создана резервная копия $RESOLV_CONF"
    fi

    cat <<EOF > "$RESOLV_CONF"
nameserver $dns1
nameserver $dns2
EOF
    if [ $? -eq 0 ]; then
        log "DNS успешно прописан в $RESOLV_CONF: $provider"
        exit 0
    else
        log "Ошибка: не удалось записать DNS в $RESOLV_CONF ($provider)"
        exit 1
    fi
}

# Сброс DNS
unset_dns() {
    log "Сброс DNS"

    # Через NetworkManager
    if [ -f "$RESOLV_CONF" ] && grep -q "Generated by NetworkManager" "$RESOLV_CONF" && command -v nmcli >/dev/null; then
        active_con=$(nmcli -t -f NAME con show --active | head -n1)
        if [ -n "$active_con" ]; then
            nmcli con mod "$active_con" ipv4.ignore-auto-dns no
            nmcli con mod "$active_con" ipv4.dns "" && nmcli con up "$active_con"
            if [ $? -eq 0 ]; then
                log "DNS сброшен через nmcli для $active_con"
                exit 0
            else
                log "Ошибка: не удалось сбросить DNS через nmcli"
                exit 1
            fi
        else
            log "Ошибка: активное соединение NetworkManager не найдено"
            exit 1
        fi
    fi

    # Восстановление из бэкапа
    if [ -f "$BACKUP_RESOLV_CONF" ]; then
        cp "$BACKUP_RESOLV_CONF" "$RESOLV_CONF" && rm -f "$BACKUP_RESOLV_CONF"
        if [ $? -eq 0 ]; then
            log "Восстановлен оригинальный $RESOLV_CONF"
            exit 0
        else
            log "Ошибка: не удалось восстановить $RESOLV_CONF"
            exit 1
        fi
    else
        # Дефолтные DNS
        cat <<EOF > "$RESOLV_CONF"
nameserver 8.8.8.8
nameserver 1.1.1.1
EOF
        if [ $? -eq 0 ]; then
            log "Установлены дефолтные DNS (Google/Cloudflare)"
            exit 0
        else
            log "Ошибка: не удалось записать дефолтные DNS"
            exit 1
        fi
    fi
}

# === Основная логика ===
case "$1" in
    set)
        case "$2" in
            xbox)
                set_dns "176.99.11.77" "80.78.247.254" "xbox-dns.ru"
                ;;
            cloudflare)
                set_dns "1.1.1.1" "1.0.0.1" "Cloudflare"
                ;;
            *)
                log "Ошибка: неизвестный провайдер '$2', используйте 'xbox' или 'cloudflare'"
                echo "Использование: $0 set {xbox|cloudflare}" >&2
                exit 1
                ;;
        esac
        ;;
    unset)
        unset_dns
        ;;
    *)
        log "Ошибка: неверный аргумент '$1', ожидается 'set' или 'unset'"
        echo "Использование: $0 {set {xbox|cloudflare}|unset}" >&2
        exit 1
        ;;
esac
